# Generated by Django 6.0.3 on 2026-03-08 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('registro_conselho', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('porcentagem_comissao', models.DecimalField(decimal_places=2, default=40.0, help_text='% por atendimento', max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PILATES', 'Pilates'), ('FISIO', 'Fisioterapia'), ('AVALIACAO', 'Avaliação'), ('OUTRO', 'Outro')], max_length=20)),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('preco_padrao', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('FALTA', 'Falta')], default='AGENDADO', max_length=20)),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='core.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('OUTRO', 'Outro')], max_length=20)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pago', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissao', to='core.atendimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comissoes', to='core.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(blank=True, null=True)),
                ('historia_doenca_atual', models.TextField(blank=True, null=True)),
                ('antecedentes_pessoais', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('medicacoes_uso', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('habitos_vida', models.TextField(blank=True, help_text='Ex: sono, alimentação, tabagismo, álcool, atividade física', null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frequencia_cardiaca', models.PositiveIntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.PositiveIntegerField(blank=True, null=True)),
                ('inspecao_postural', models.TextField(blank=True, null=True)),
                ('mobilidade_articular', models.TextField(blank=True, null=True)),
                ('forca_muscular', models.TextField(blank=True, null=True)),
                ('testes_especiais', models.TextField(blank=True, null=True)),
                ('dor_localizacao', models.TextField(blank=True, null=True)),
                ('dor_intensidade', models.CharField(blank=True, help_text='Escala numérica, EVA etc.', max_length=50, null=True)),
                ('descricao_sessao', models.TextField(blank=True, null=True)),
                ('conduta', models.TextField(blank=True, null=True)),
                ('orientacoes_paciente', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='core.atendimento')),
            ],
        ),
    ]
